services:
  sofa-shop-node:
    build: .
    ports:
      - "3000:3000"  # Expose your app
    environment:
      - NODE_ENV=production
      - MONGO_HOST=sofa-shop-mongo
      - MONGO_PORT=27017
      - MONGO_USER=Lydia
      - MONGO_PASSWORD=shop88
      - MONGO_DEFAULT_DATABASE=sofa-node-shop
      - STRIPE_KEY=sk_test_51JFeduJqMBxMksyPct4mxUGy49QOmlSDo18LJjFL9Sb95mt88tdEtjzC30pwVGjQK
      # Add any other environment variables you want to pull from here
    depends_on:
      - sofa-shop-mongo
    restart: unless-stopped

  sofa-shop-mongo:
    image: mongo
    container_name: sofa-shop-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db  # Persistent storage for MongoDB
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js # Mount the script
    environment:
      MONGO_INITDB_DATABASE: sofa-node-shop
      MONGO_INITDB_ROOT_USERNAME: mongo-admin
      MONGO_INITDB_ROOT_PASSWORD: shop88
    restart: unless-stopped

volumes:
  db-data: